version: '3.9'

services:
  flask:
    build: backend
    image: flask
    restart: unless-stopped
    ports:
    - "5000:5000"
    volumes:
    - appdata:/python-flask
    depends_on:
      - mongo
    networks:
      - frontend
      - backend

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo
    volumes:
    - mongodbdata:/data/db
    networks:
      - backend

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
