version: '3.9'
services:
  flask:
    build:
      context: backend
      dockerfile: Dockerfile
    image: python:3.9.5
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - appdata:/var/www
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    command: mongod
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
