version: '3.9'

services:

  react:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: node
    tty: true
    container_name: react
    ports:
      - "3000:3000"
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend

  flask:
    build: backend
    image: flask
    restart: unless-stopped
    container_name: flask
    ports:
      - "5000:5000"
    volumes:
    - appdata:/python-flask
    depends_on:
      - mongo
    networks:
      - frontend
      - backend

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo
    volumes:
    - mongodbdata:/data/db
    networks:
      - backend

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
