version : '3.8'
services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    container_name: mongoDB
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27027"
    volumes:
      - backendDB:/data/db

volumes:
  backendDB:
    driver: local
