# Generated by Django 3.2.9 on 2021-12-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
