# Generated by Django 3.2.9 on 2021-11-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211113_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
