# Generated by Django 3.2.9 on 2021-12-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_story_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='time',
            new_name='time_start',
        ),
        migrations.AddField(
            model_name='story',
            name='time_end',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='story',
            name='multimedia',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='numberOfComments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='numberOfLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
