# Generated by Django 3.2.9 on 2021-12-20 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=500)),
                ('reported_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_id', to=settings.AUTH_USER_MODEL)),
                ('reporter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
