# Generated by Django 3.2.9 on 2021-12-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211207_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='time_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
