# Generated by Django 3.2.9 on 2021-12-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_story_time_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
