# Generated by Django 3.2.9 on 2021-12-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment_id',
            field=models.IntegerField(null=True),
        ),
    ]
