# Generated by Django 3.2.9 on 2021-12-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_pinnedcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=500)),
                ('admin_password', models.CharField(max_length=500)),
            ],
        ),
    ]
