# Generated by Django 3.2.9 on 2021-12-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='login_hash',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
