# Generated by Django 3.2.9 on 2021-12-25 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0014_admin_login_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(default='', max_length=3000)),
                ('multimedia', models.CharField(default='', max_length=100)),
                ('time_start', models.DateField()),
                ('time_end', models.DateField(blank=True, null=True)),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('numberOfLikes', models.IntegerField(default=0)),
                ('numberOfComments', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
