# Generated by Django 3.2.9 on 2021-12-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_activitystream_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
