# Generated by Django 3.2.9 on 2021-12-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_followrequest'),
        ('user', '0019_remove_profile_location'),
    ]

    operations = [
    ]
